require: rubocop-rails
Layout/EmptyLineAfterMagicComment:
  Description: Checks if there is empty line after magic comment.
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  Description: Do not use space inside array brackets
  Enabled: true
Layout/SpaceInsidePercentLiteralDelimiters:
  Description: Checks if there is unnecessary space in Percent Literal Delimeters.
  Enabled: true
Rails/FilePath:
  Description: This cop is used to identify usages of file path joining process to use ‘Rails.root.join` clause. It is used to add uniformity when joining paths.
  Enabled: true
  EnforcedStyle: slashes
Style/Documentation:
  Description: Checks if there is comment on the top of the class.
  Enabled: false
Style/FrozenStringLiteralComment:
  Description: Checks if there is frozen_string_literal magic comment on the top of the file.
  Enabled: true
Style/GlobalStdStream:
  Description: Use $stdout instead of STDOUT.
  Enabled: false
Style/RedundantFetchBlock:
  Description: Identifies places where ‘fetch(key) { value }` can be replaced by `fetch(key, value)`.
  Enabled: true
Style/RedundantInterpolation:
  Description: Checks for strings that are just an interpolated expression.
  Enabled: false
Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  Enabled: true
  EnforcedStyle: double_quotes
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  SupportedStyles:
  - single_quotes
  - double_quotes
Style/StringLiteralsInInterpolation:
  Description: Checks that quotes inside string, symbol, and regexp interpolations match the configured preference.
  Enabled: true
  EnforcedStyle: double_quotes
  SupportedStyles:
  - single_quotes
  - double_quotes
Style/SymbolArray:
  Description: Use %i or %I for arrays of symbols.
  Enabled: false
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#percent-i
